{"uuid":"23496876-1c7f-4158-9bd5-496570b0a0ef","historyId":"59355ee3ccaa17991ce5d44df13601e3","fullName":"com.qa.store.tests.LoginPageTest.loginPageURLTest","labels":[{"name":"package","value":"com.qa.store.tests.LoginPageTest"},{"name":"testClass","value":"com.qa.store.tests.LoginPageTest"},{"name":"testMethod","value":"loginPageURLTest"},{"name":"parentSuite","value":"Open Cart Regression Suite"},{"name":"suite","value":"Login Page Test"},{"name":"subSuite","value":"com.qa.store.tests.LoginPageTest"},{"name":"host","value":"DESKTOP-2FPLA3S"},{"name":"thread","value":"1548@DESKTOP-2FPLA3S.TestNG-tests-1(19)"},{"name":"framework","value":"testng"},{"name":"language","value":"java"},{"name":"story","value":"US 101: Design login page features for open cart application"},{"name":"feature","value":"Feature 201: Adding login features"},{"name":"epic","value":"Epic 100: Design open cart login page"},{"name":"severity","value":"minor"}],"links":[],"name":"loginPageURLTest","status":"skipped","statusDetails":{"known":false,"muted":false,"flaky":false,"message":"Could not start a new session. Possible causes are invalid address of the remote server or browser start-up failure.\nBuild info: version: '4.0.0-alpha-3', revision: '8c567de6dc'\nSystem info: host: 'DESKTOP-2FPLA3S', ip: '192.168.93.177', os.name: 'Windows 11', os.arch: 'amd64', os.version: '10.0', java.version: '17.0.7'\nDriver info: driver.version: RemoteWebDriver","trace":"org.openqa.selenium.remote.UnreachableBrowserException: Could not start a new session. Possible causes are invalid address of the remote server or browser start-up failure.\nBuild info: version: '4.0.0-alpha-3', revision: '8c567de6dc'\nSystem info: host: 'DESKTOP-2FPLA3S', ip: '192.168.93.177', os.name: 'Windows 11', os.arch: 'amd64', os.version: '10.0', java.version: '17.0.7'\nDriver info: driver.version: RemoteWebDriver\r\n\tat org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:597)\r\n\tat org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:210)\r\n\tat org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:130)\r\n\tat org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:143)\r\n\tat com.qa.store.factory.DriverFactory.init_remoteDriver(DriverFactory.java:106)\r\n\tat com.qa.store.factory.DriverFactory.initDriver(DriverFactory.java:50)\r\n\tat com.qa.store.base.BaseTest.setup(BaseTest.java:49)\r\n\tat java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\r\n\tat java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)\r\n\tat java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\r\n\tat java.base/java.lang.reflect.Method.invoke(Method.java:568)\r\n\tat org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:135)\r\n\tat org.testng.internal.invokers.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:65)\r\n\tat org.testng.internal.invokers.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:381)\r\n\tat org.testng.internal.invokers.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:319)\r\n\tat org.testng.TestRunner.invokeTestConfigurations(TestRunner.java:645)\r\n\tat org.testng.TestRunner.beforeRun(TestRunner.java:634)\r\n\tat org.testng.TestRunner.run(TestRunner.java:596)\r\n\tat org.testng.SuiteRunner.runTest(SuiteRunner.java:429)\r\n\tat org.testng.SuiteRunner.access$000(SuiteRunner.java:32)\r\n\tat org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:467)\r\n\tat org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:58)\r\n\tat java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)\r\n\tat java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)\r\n\tat java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)\r\n\tat java.base/java.lang.Thread.run(Thread.java:833)\r\nCaused by: java.io.UncheckedIOException: java.net.ConnectException: Failed to connect to /43.204.142.27:4444\r\n\tat org.openqa.selenium.remote.http.okhttp.OkHandler.makeCall(OkHandler.java:63)\r\n\tat org.openqa.selenium.remote.http.AddSeleniumUserAgent.lambda$apply$0(AddSeleniumUserAgent.java:42)\r\n\tat org.openqa.selenium.remote.http.Filter.lambda$andFinally$1(Filter.java:55)\r\n\tat org.openqa.selenium.remote.http.okhttp.OkHandler.execute(OkHandler.java:52)\r\n\tat org.openqa.selenium.remote.http.AddSeleniumUserAgent.lambda$apply$0(AddSeleniumUserAgent.java:42)\r\n\tat org.openqa.selenium.remote.http.Filter.lambda$andFinally$1(Filter.java:55)\r\n\tat org.openqa.selenium.remote.http.okhttp.OkHttpClient.execute(OkHttpClient.java:45)\r\n\tat org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:106)\r\n\tat org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:75)\r\n\tat org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:139)\r\n\tat org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:576)\r\n\t... 25 more\r\nCaused by: java.net.ConnectException: Failed to connect to /43.204.142.27:4444\r\n\tat okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.kt:270)\r\n\tat okhttp3.internal.connection.RealConnection.connect(RealConnection.kt:176)\r\n\tat okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.kt:236)\r\n\tat okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.kt:109)\r\n\tat okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.kt:77)\r\n\tat okhttp3.internal.connection.Transmitter.newExchange$okhttp(Transmitter.kt:162)\r\n\tat okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:35)\r\n\tat okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:112)\r\n\tat okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:87)\r\n\tat okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:82)\r\n\tat okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:112)\r\n\tat okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:87)\r\n\tat okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:84)\r\n\tat okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:112)\r\n\tat okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:71)\r\n\tat okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:112)\r\n\tat okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:87)\r\n\tat okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.kt:184)\r\n\tat okhttp3.RealCall.execute(RealCall.kt:66)\r\n\tat org.openqa.selenium.remote.http.okhttp.OkHandler.makeCall(OkHandler.java:60)\r\n\t... 35 more\r\nCaused by: java.net.ConnectException: Connection timed out: no further information\r\n\tat java.base/sun.nio.ch.Net.pollConnect(Native Method)\r\n\tat java.base/sun.nio.ch.Net.pollConnectNow(Net.java:672)\r\n\tat java.base/sun.nio.ch.NioSocketImpl.timedFinishConnect(NioSocketImpl.java:549)\r\n\tat java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:597)\r\n\tat java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327)\r\n\tat java.base/java.net.Socket.connect(Socket.java:633)\r\n\tat okhttp3.internal.platform.Platform.connectSocket(Platform.kt:126)\r\n\tat okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.kt:268)\r\n\t... 54 more\r\n"},"stage":"finished","description":"Checking login page URL....","steps":[],"attachments":[],"parameters":[{"name":"browser","value":"chrome"}],"start":1717305517370,"stop":1717305517371}